import { green } from "../../deps.ts";
import { log } from "../../utils/log.ts";
import { NestCLIError } from "../../utils/error.ts";
import { ensureFile, exists as exists_, join } from "../../deps.ts";
import { readJson, writeJson } from "../../utils/json.ts";
import { PATH as DIR_PATH } from "./nest.ts";
import { envHOMEDIR } from "../../utils/env.ts";
import { assertUserManager } from "../parse/user-manager.ts";
import type { Json, User, UserManager } from "../../utils/types.ts";

export const FILE = "users.json";
export const PATH = join(envHOMEDIR(), DIR_PATH, FILE);

/** Test whether or not the users file exists by checking with the file system */
export function exists(): Promise<boolean> {
  return exists_(PATH);
}

/** Ensures that the users file exists. */
export async function ensure(): Promise<void> {
  await ensureFile(PATH);
}

/** Reads the users file. */
export function read(): Promise<string> {
  return Deno.readTextFile(PATH);
}

/** Reads and parses the users file. */
export async function parse(path = PATH): Promise<UserManager> {
  const json = await readJson(path) as Json;

  return assertUserManager(json, FILE);
}

/** Writes a user object to the users file. */
export async function write(
  content: UserManager,
  path = PATH,
) {
  await writeJson(path, {
    $comment: "THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
    ...content,
  }, { spaces: 2 });
}

/** Checks if an user is logged in and returns a user manager object.
 * If not logged in, throws an error. */
export async function ensureLogged(): Promise<UserManager> {
  let manager: UserManager;
  if (
    !await exists() ||
    (manager = await parse()).activeUser === ""
  ) {
    log.error("No user logged in, use", green("nest login"), "to add users.");
    throw new NestCLIError("No user logged in (login)");
  }
  return manager;
}

/** Get active user. Throws if no user is logged in. */
export async function getActive(): Promise<User> {
  const { users, activeUser } = await ensureLogged();
  return users[activeUser];
}
