import { exists, join } from "../deps.ts";
import { readJson, writeJson } from "../utilities/json.ts";
import { NEST_DIRECTORY } from "./nest.ts";
import { assertProject } from "./parse/project.ts";
import type { Json, Project } from "../utilities/types.ts";

export const DATA_FILE = "data.json";
export const DATA_PATH = join(NEST_DIRECTORY, DATA_FILE);

export function dataJsonExists() {
  return exists(DATA_PATH);
}

/** Reads the `data.json` file. */
export function readDataJson(): Promise<string> {
  return Deno.readTextFile(DATA_PATH);
}

/** Reads and parses the `data.json` file. */
export async function parseDataJson(path = DATA_PATH): Promise<Project> {
  const json = await readJson(path) as Json;

  return assertProject(json, DATA_FILE);
}

export async function writeDataJson(content: Project, path = DATA_PATH) {
  await writeJson(path, {
    $comment: "THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
    ...content,
  }, { spaces: 2 });
}
